### ISSUE TITLE
Make a better "how I can help" page

### ISSUE THREAD

**Issue by amandamcg** [hackforla/food-oasis-la#120]
Create a single clear page with CTAs based on interests

**Comment by amandamcg** [comment]
From @ravencofer <img width="476" alt="screen shot 2017-07-18 at 7 07 27 pm" src="https://user-images.githubusercontent.com/8716226/28347611-fdccb8b8-6bec-11e7-94a1-f39a333abe2d.png">

**Comment by SomeRandom42** [comment]
Hey I made this page on staging willing to do more if I can get more instructions and information. I think it also needs a link in he footer if I can get further instructions.
Link: https://staging.foodoasis.la/help/

**Comment by jimthoburn** [comment]
Thanks, Patrick!
