### ISSUE TITLE
Translate the home page into Spanish

### ISSUE THREAD

**Issue by jimthoburn** [hackforla/food-oasis-la#14]
The content for the Spanish home page is in this file…
https://github.com/foodoasisla/site/blob/master/es/index.md

And you can view the page here…
https://foodoasis.la/es/

[Halina](https://github.com/hvz90) can help with the translation.

![spanish-home-page](https://cloud.githubusercontent.com/assets/926616/21304237/8ea90bfa-c578-11e6-8e5c-0022bb623f9e.png)

**Comment by ExperimentsInHonesty** [comment]
Once the site is redeveloped we will re-translate it.
