### ISSUE TITLE
Small fixes for Add Location page using GitHub, in assets/js/github-backend.js

### ISSUE THREAD

**Issue by LearningNerd** [hackforla/food-oasis-la#41]
Throwing these all into one issue for now:

- [X] **DONE:** Unicode characters break the base64 encoding (`window.btoa`) used when creating the new file on GitHub. **To fix this:** See https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa (Note: the Mavo project uses the quick fix using `encodeURIComponent`)

-  [ ] **Bug:** After user logs in with GitHub, if they refresh the page, the app tries to log them in again using the temporary code that's still in the URL params, which throws a 401 error "Request failed: Unauthorized". **To fix this:** either remove the temporary code from the URL after the user is successfully authenticated, and/or implement user sessions (maybe just use localstorage?)

-  [ ] **Bug:** If user has already submitted something, the link to their pull request won't work (GitHub sends a 422 error because the pull request already exists). **To fix this:** check if user already has a pull request open and if so, grab the link (instead of trying to create a new pull request)!

-  [ ] **Code improvement:** No more global variables! Or just wrap it in an IIFE.

-  [ ] **Code improvement:** Add a polyfill for Promises and also for ` element.classList` and any other newer JS features for wider browser support.

-  [x] **Functionality improvement:** Use nice HTML form with all metadata in separate fields and put all those fields into properly formatted YAML/front matter when creating the new file!

-  [x] **Functionality improvement:** Create file name and Pull Request title / body based on the user input (like maybe make the filename a URL-encoded version of the suggested location name)

**Comment by jimthoburn** [comment]
Here are some more todo’s for this one…

1. Add a link to the “add” page.
2. Save the locations by category. For example, if someone enters `Food Pantry` we would save the location in the `_food-pantry` folder.
3. Update the Jekyll code so that new locations get added to the map automatically.
4. Make the UI nicer (i.e. use separate form fields for each item of data)
