### ISSUE TITLE
Make a “Claim Business” web form

### ISSUE THREAD

**Issue by jimthoburn** [hackforla/food-oasis-la#68]
The “claim business” button on the location page currently opens the user’s email program and auto-fills a message to us. This might be improved by showing a web form instead.

We could start with something simple, like a [Google Form](https://www.google.com/forms/about/) or [Formspree form](https://formspree.io).

_TBD: What fields should this web form have? (Raven, Amanda, or Josh may have recommendations)_

You can see an example button here…
https://foodoasis.la/community-garden/spring-street/

The template for the location page is here…
https://github.com/foodoasisla/site/blob/master/_layouts/location-details.html

Bonus Points: Use the same form style for the “Report Issue” button (@joshuazrobins may have recommendations for this.)

**Comment by ExperimentsInHonesty** [comment]
This will be replaced with a full login/authorization module
